name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: . # or the path to your Dockerfile
                  file: ./Dockerfile # adjust if your Dockerfile is in a different location
                  push: true
                  tags: ignaskav/aquawise:fe-${{ github.run_number }}
